/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacote.visao;


import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;


/**
 *
 * @author Ligia
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        itemMenuCadastrarPessoa = new javax.swing.JMenuItem();
        itemMenuCadastrar1 = new javax.swing.JMenuItem();
        itemMenuCadastrarLaboratorio = new javax.swing.JMenuItem();
        itemMenuCadastrarFuncionario = new javax.swing.JMenuItem();
        itemMenuCadastrarFornecedores = new javax.swing.JMenuItem();
        menuVisualizarPessoa = new javax.swing.JMenu();
        jMenuItemVisualizarPessoa = new javax.swing.JMenuItem();
        jMenuItemVisualizarMedicamento = new javax.swing.JMenuItem();
        jMenuItemVisualizarLaboratorio = new javax.swing.JMenuItem();
        jMenuItemVisualizarFuncionario = new javax.swing.JMenuItem();
        jMenuItemVisualizarFornecedores = new javax.swing.JMenuItem();
        menuAlterarPessoa = new javax.swing.JMenu();
        jMenuItemAlterarPessoa = new javax.swing.JMenuItem();
        jMenuItemAlterarMedicamento = new javax.swing.JMenuItem();
        jMenuItemAlterarLaboratorio = new javax.swing.JMenuItem();
        jMenuItemAlterarFuncionario = new javax.swing.JMenuItem();
        jMenuItemAlterarFornecedores = new javax.swing.JMenuItem();
        menuExcluirPessoa = new javax.swing.JMenu();
        jMenuItemDeletarPessoa = new javax.swing.JMenuItem();
        jMenuItemDeletarMedicamento = new javax.swing.JMenuItem();
        jMenuItemDeletarLaboratorio = new javax.swing.JMenuItem();
        jMenuItemDeletarFuncionario = new javax.swing.JMenuItem();
        jMenuItemDeletarFornecedores = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/img/iftm.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        menuCadastro.setText("Cadastro");
        menuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroActionPerformed(evt);
            }
        });

        itemMenuCadastrarPessoa.setText("Cadastrar Pessoa");
        itemMenuCadastrarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadastrarPessoaActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuCadastrarPessoa);

        itemMenuCadastrar1.setText("Cadastrar Medicamento");
        itemMenuCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadastrar1ActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuCadastrar1);

        itemMenuCadastrarLaboratorio.setText("Cadastrar Laboratorio");
        itemMenuCadastrarLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadastrarLaboratorioActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuCadastrarLaboratorio);

        itemMenuCadastrarFuncionario.setText("Cadastrar Funcionario");
        itemMenuCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadastrarFuncionarioActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuCadastrarFuncionario);

        itemMenuCadastrarFornecedores.setText("Cadastrar Fornecedores");
        itemMenuCadastrarFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadastrarFornecedoresActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuCadastrarFornecedores);

        jMenuBar1.add(menuCadastro);

        menuVisualizarPessoa.setText("Visualizar");

        jMenuItemVisualizarPessoa.setText("Visualizar Pessoa");
        jMenuItemVisualizarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisualizarPessoaActionPerformed(evt);
            }
        });
        menuVisualizarPessoa.add(jMenuItemVisualizarPessoa);

        jMenuItemVisualizarMedicamento.setText("Visulizar Medicamento");
        jMenuItemVisualizarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisualizarMedicamentoActionPerformed(evt);
            }
        });
        menuVisualizarPessoa.add(jMenuItemVisualizarMedicamento);

        jMenuItemVisualizarLaboratorio.setText("Visualizar Laboratório");
        jMenuItemVisualizarLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisualizarLaboratorioActionPerformed(evt);
            }
        });
        menuVisualizarPessoa.add(jMenuItemVisualizarLaboratorio);

        jMenuItemVisualizarFuncionario.setText("Visualizar Funcionario");
        jMenuItemVisualizarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisualizarFuncionarioActionPerformed(evt);
            }
        });
        menuVisualizarPessoa.add(jMenuItemVisualizarFuncionario);

        jMenuItemVisualizarFornecedores.setText("Visualizar Fornecedores");
        jMenuItemVisualizarFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisualizarFornecedoresActionPerformed(evt);
            }
        });
        menuVisualizarPessoa.add(jMenuItemVisualizarFornecedores);

        jMenuBar1.add(menuVisualizarPessoa);

        menuAlterarPessoa.setText("Alterar");

        jMenuItemAlterarPessoa.setText("Alterar Pessoa");
        jMenuItemAlterarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarPessoaActionPerformed(evt);
            }
        });
        menuAlterarPessoa.add(jMenuItemAlterarPessoa);

        jMenuItemAlterarMedicamento.setText("Alterar Medicamento");
        jMenuItemAlterarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarMedicamentoActionPerformed(evt);
            }
        });
        menuAlterarPessoa.add(jMenuItemAlterarMedicamento);

        jMenuItemAlterarLaboratorio.setText("Alterar Laboratorio");
        jMenuItemAlterarLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarLaboratorioActionPerformed(evt);
            }
        });
        menuAlterarPessoa.add(jMenuItemAlterarLaboratorio);

        jMenuItemAlterarFuncionario.setText("Alterar Funcionario");
        jMenuItemAlterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarFuncionarioActionPerformed(evt);
            }
        });
        menuAlterarPessoa.add(jMenuItemAlterarFuncionario);

        jMenuItemAlterarFornecedores.setText("Alterar Fornecedores");
        jMenuItemAlterarFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarFornecedoresActionPerformed(evt);
            }
        });
        menuAlterarPessoa.add(jMenuItemAlterarFornecedores);

        jMenuBar1.add(menuAlterarPessoa);

        menuExcluirPessoa.setText("Excluir");
        menuExcluirPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuExcluirPessoaMouseClicked(evt);
            }
        });
        menuExcluirPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExcluirPessoaActionPerformed(evt);
            }
        });

        jMenuItemDeletarPessoa.setText("Deletar Pessoa");
        jMenuItemDeletarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeletarPessoaActionPerformed(evt);
            }
        });
        menuExcluirPessoa.add(jMenuItemDeletarPessoa);

        jMenuItemDeletarMedicamento.setText("Deletar Medicamento");
        jMenuItemDeletarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeletarMedicamentoActionPerformed(evt);
            }
        });
        menuExcluirPessoa.add(jMenuItemDeletarMedicamento);

        jMenuItemDeletarLaboratorio.setText("Deletar Laboratório");
        jMenuItemDeletarLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeletarLaboratorioActionPerformed(evt);
            }
        });
        menuExcluirPessoa.add(jMenuItemDeletarLaboratorio);

        jMenuItemDeletarFuncionario.setText("Deletar Funcionario");
        jMenuItemDeletarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeletarFuncionarioActionPerformed(evt);
            }
        });
        menuExcluirPessoa.add(jMenuItemDeletarFuncionario);

        jMenuItemDeletarFornecedores.setText("Deletar Fornecedores");
        jMenuItemDeletarFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeletarFornecedoresActionPerformed(evt);
            }
        });
        menuExcluirPessoa.add(jMenuItemDeletarFornecedores);

        jMenuBar1.add(menuExcluirPessoa);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuCadastrarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadastrarPessoaActionPerformed
        new Cadastro().setVisible(true);
        dispose();
    }//GEN-LAST:event_itemMenuCadastrarPessoaActionPerformed

    private void jMenuItemVisualizarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisualizarPessoaActionPerformed
        new Visualizar().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemVisualizarPessoaActionPerformed

    private void jMenuItemAlterarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarPessoaActionPerformed
        new Atualizar().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemAlterarPessoaActionPerformed

    private void menuExcluirPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuExcluirPessoaMouseClicked
        new Deletar().setVisible(true);
        dispose();
    }//GEN-LAST:event_menuExcluirPessoaMouseClicked

    private void itemMenuCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadastrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMenuCadastrar1ActionPerformed

    private void itemMenuCadastrarLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadastrarLaboratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMenuCadastrarLaboratorioActionPerformed

    private void itemMenuCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadastrarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMenuCadastrarFuncionarioActionPerformed

    private void itemMenuCadastrarFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadastrarFornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMenuCadastrarFornecedoresActionPerformed

    private void jMenuItemVisualizarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisualizarMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemVisualizarMedicamentoActionPerformed

    private void jMenuItemVisualizarLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisualizarLaboratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemVisualizarLaboratorioActionPerformed

    private void jMenuItemVisualizarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisualizarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemVisualizarFuncionarioActionPerformed

    private void jMenuItemVisualizarFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisualizarFornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemVisualizarFornecedoresActionPerformed

    private void jMenuItemAlterarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAlterarMedicamentoActionPerformed

    private void jMenuItemAlterarLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarLaboratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAlterarLaboratorioActionPerformed

    private void jMenuItemAlterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAlterarFuncionarioActionPerformed

    private void jMenuItemAlterarFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarFornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAlterarFornecedoresActionPerformed

    private void jMenuItemDeletarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeletarPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDeletarPessoaActionPerformed

    private void jMenuItemDeletarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeletarMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDeletarMedicamentoActionPerformed

    private void jMenuItemDeletarLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeletarLaboratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDeletarLaboratorioActionPerformed

    private void jMenuItemDeletarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeletarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDeletarFuncionarioActionPerformed

    private void jMenuItemDeletarFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeletarFornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDeletarFornecedoresActionPerformed

    private void menuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastroActionPerformed

    private void menuExcluirPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExcluirPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuExcluirPessoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemMenuCadastrar1;
    private javax.swing.JMenuItem itemMenuCadastrarFornecedores;
    private javax.swing.JMenuItem itemMenuCadastrarFuncionario;
    private javax.swing.JMenuItem itemMenuCadastrarLaboratorio;
    private javax.swing.JMenuItem itemMenuCadastrarPessoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAlterarFornecedores;
    private javax.swing.JMenuItem jMenuItemAlterarFuncionario;
    private javax.swing.JMenuItem jMenuItemAlterarLaboratorio;
    private javax.swing.JMenuItem jMenuItemAlterarMedicamento;
    private javax.swing.JMenuItem jMenuItemAlterarPessoa;
    private javax.swing.JMenuItem jMenuItemDeletarFornecedores;
    private javax.swing.JMenuItem jMenuItemDeletarFuncionario;
    private javax.swing.JMenuItem jMenuItemDeletarLaboratorio;
    private javax.swing.JMenuItem jMenuItemDeletarMedicamento;
    private javax.swing.JMenuItem jMenuItemDeletarPessoa;
    private javax.swing.JMenuItem jMenuItemVisualizarFornecedores;
    private javax.swing.JMenuItem jMenuItemVisualizarFuncionario;
    private javax.swing.JMenuItem jMenuItemVisualizarLaboratorio;
    private javax.swing.JMenuItem jMenuItemVisualizarMedicamento;
    private javax.swing.JMenuItem jMenuItemVisualizarPessoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAlterarPessoa;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuExcluirPessoa;
    private javax.swing.JMenu menuVisualizarPessoa;
    // End of variables declaration//GEN-END:variables
}
